reupload app later after rename - just for testing

diff --git a/.github/workflows/frozen_binaries.yml b/.github/workflows/frozen_binaries.yml
--- a/.github/workflows/frozen_binaries.yml
+++ b/.github/workflows/frozen_binaries.yml
@@ -152,6 +152,7 @@ jobs:
 
       - name: Install dependencies
         run: |
+          pip install "setuptools<81"
           pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/numpy-1.26.2-cp312-cp312-macosx_10_9_universal2.whl
           pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/h5py-3.10.0-cp312-cp312-macosx_11_0_universal2.whl
           pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/psutil-5.9.6-cp312-abi3-macosx_10_9_universal2.whl
@@ -209,60 +210,60 @@ jobs:
           name: macos-pyinstaller-artifacts
           path: ./downloaded-artifacts
 
-      ### dmg
-
-      - name: Mount the DMG
-        run: |
-          hdiutil attach ./downloaded-artifacts/PyMca5.9.4.dmg -mountpoint /Volumes/PyMcaApp
-
-      - name: Copy .app to /Applications
-        run: |
-          sudo cp -R "/Volumes/PyMcaApp/PyMca5.9.4.app" /Applications/
-          ls -l /Applications/PyMca5.9.4.app/Contents/MacOS
-          ls -l /Applications/PyMca5.9.4.app/Contents/Frameworks/h5py
-
-      - name: Verify .app existence
-        run: test -d /Applications/PyMca5.9.4.app
-
-      - name: Make main binary executable
-        run: chmod +x /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain
-
-      - name: Run the app to check it launches
-        run: |
-          set -e
-      
-          echo "Launching PyMcaMain..."
-      
-          # Start the app in the background
-          /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain &
-          APP_PID=$!
-      
-          echo "App started with PID $APP_PID"
-      
-          # Wait up to 3 minutes (180 seconds) for it to crash or hang
-          for i in {1..180}; do
-            if ! ps -p $APP_PID > /dev/null; then
-              echo "App exited early. Checking exit code..."
-              wait $APP_PID
-              EXIT_CODE=$?
-              if [ $EXIT_CODE -ne 0 ]; then
-                echo "App exited with error code $EXIT_CODE"
-                exit $EXIT_CODE
-              else
-                echo "App exited cleanly before 5 minutes."
-                exit 0
-              fi
-            fi
-            sleep 1
-          done
-      
-          echo "App ran for 5 minutes without crashing. Killing it now..."
-          kill $APP_PID || true
-          wait $APP_PID || true
-          echo "App test complete."
-
-      - name: Cleanup
-        run: sudo rm -rf /Applications/PyMca5.9.4.app
+#      ### dmg
+#
+#      - name: Mount the DMG
+#        run: |
+#          hdiutil attach ./downloaded-artifacts/PyMca5.9.4.dmg -mountpoint /Volumes/PyMcaApp
+#
+#      - name: Copy .app to /Applications
+#        run: |
+#          sudo cp -R "/Volumes/PyMcaApp/PyMca5.9.4.app" /Applications/
+#          ls -l /Applications/PyMca5.9.4.app/Contents/MacOS
+#          ls -l /Applications/PyMca5.9.4.app/Contents/Frameworks/h5py
+#
+#      - name: Verify .app existence
+#        run: test -d /Applications/PyMca5.9.4.app
+#
+#      - name: Make main binary executable
+#        run: chmod +x /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain
+#
+#      - name: Run the app to check it launches
+#        run: |
+#          set -e
+#
+#          echo "Launching PyMcaMain..."
+#
+#          # Start the app in the background
+#          /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain &
+#          APP_PID=$!
+#
+#          echo "App started with PID $APP_PID"
+#
+#          # Wait up to 3 minutes (180 seconds) for it to crash or hang
+#          for i in {1..180}; do
+#            if ! ps -p $APP_PID > /dev/null; then
+#              echo "App exited early. Checking exit code..."
+#              wait $APP_PID
+#              EXIT_CODE=$?
+#              if [ $EXIT_CODE -ne 0 ]; then
+#                echo "App exited with error code $EXIT_CODE"
+#                exit $EXIT_CODE
+#              else
+#                echo "App exited cleanly before 5 minutes."
+#                exit 0
+#              fi
+#            fi
+#            sleep 1
+#          done
+#
+#          echo "App ran for 5 minutes without crashing. Killing it now..."
+#          kill $APP_PID || true
+#          wait $APP_PID || true
+#          echo "App test complete."
+#
+#      - name: Cleanup
+#        run: sudo rm -rf /Applications/PyMca5.9.4.app
 
       ### app
 
